/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gwcd_sy_aacdecode_LibFaad */

#ifndef _Included_com_gwcd_sy_aacdecode_LibFaad
#define _Included_com_gwcd_sy_aacdecode_LibFaad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gwcd_sy_aacdecode_LibFaad
 * Method:    openFaad
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gwcd_sy_aacdecode_LibFaad_openFaad
  (JNIEnv *, jclass);

/*
 * Class:     com_gwcd_sy_aacdecode_LibFaad
 * Method:    initFaad
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_gwcd_sy_aacdecode_LibFaad_initFaad
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     com_gwcd_sy_aacdecode_LibFaad
 * Method:    decodeAAC
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gwcd_sy_aacdecode_LibFaad_decodeAAC
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_gwcd_sy_aacdecode_LibFaad
 * Method:    decodeAACFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gwcd_sy_aacdecode_LibFaad_decodeAACFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_gwcd_sy_aacdecode_LibFaad
 * Method:    colseFaad
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gwcd_sy_aacdecode_LibFaad_colseFaad
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
