/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gwcd_indiacar_utils_AudioDecoder */

#ifndef _Included_com_gwcd_indiacar_utils_AudioDecoder
#define _Included_com_gwcd_indiacar_utils_AudioDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gwcd_indiacar_utils_AudioDecoder
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gwcd_indiacar_utils_AudioDecoder_open
  (JNIEnv *, jclass);

/*
 * Class:     com_gwcd_indiacar_utils_AudioDecoder
 * Method:    init
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_com_gwcd_indiacar_utils_AudioDecoder_init
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     com_gwcd_indiacar_utils_AudioDecoder
 * Method:    decodeAAC
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_gwcd_indiacar_utils_AudioDecoder_decodeAAC
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_gwcd_indiacar_utils_AudioDecoder
 * Method:    decodeAACFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_gwcd_indiacar_utils_AudioDecoder_decodeAACFile
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     com_gwcd_indiacar_utils_AudioDecoder
 * Method:    decodeAACFile2
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_gwcd_indiacar_utils_AudioDecoder_decodeAACFile2
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     com_gwcd_indiacar_utils_AudioDecoder
 * Method:    getAACFileInfo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gwcd_indiacar_utils_AudioDecoder_getAACFileInfo
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gwcd_indiacar_utils_AudioDecoder
 * Method:    colse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gwcd_indiacar_utils_AudioDecoder_colse
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
